apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-argo-cd-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-python-argo-cd-app                 # Deployment 使用此标签选择其 Pod
  template:
    metadata:
      labels:
        app: my-python-argo-cd-app               # Pod 打上了这个标签
    spec:
      containers:
      - name: my-python-argo-cd-app
        image: 172.17.0.1:5000/my-python-argo-cd-app:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
